### ISSUE TITLE
Contribution of Flexible Conv Encoder/Decoder Base nn.Modules

### ISSUE THREAD

**Issue by NMontanaBrown** [alawryaguila/multiviewAE#4]
Hi! @alawryaguila mentioned that you might be tackling this as an enhancement/future feature.

I can contribute this if you are interested, as I have some code that handles most cases, and unit tested.

**Comment by alawryaguila** [comment]
Hi @NMontanaBrown, sounds great! Let's discuss your code, and how we can fit it into the existing framework, offline.
